### ISSUE TITLE
list queues errors out

### ISSUE THREAD

**Issue by axlroden** [StackStorm-Exchange/stackstorm-rabbitmq#1]
Tried testing a list queues on st2's own rabbitmq server:

```
status: failed (3s elapsed)
parameters:
  hosts: 127.0.0.1
result:
  127.0.0.1:
    failed: true
    return_code: 1
    stderr: "Traceback (most recent call last):
  File "/tmp/591175b5c4da5f3b1163c5e8/list_queues.py", line 80, in <module>
    result = list_queues()
  File "/tmp/591175b5c4da5f3b1163c5e8/list_queues.py", line 71, in list_queues
    value = attr_cast(value)
ValueError: invalid literal for int() with base 10: ''"
    stdout: ''
    succeeded: false
```

This is the queue:

```
+----------------------------------------------------------+----------+
|                           name                           | messages |
+----------------------------------------------------------+----------+
| amq.gen-RXRQsBxKgfwRjeqP-tCv_Q                           | 0        |
| amq.gen-gk1W1zfjSNEx8IvxGnJnLg                           | 0        |
| amq.gen-vbw-8fp7cw33MwxncC-YGg                           | 0        |
| mistral_engine                                           | 0        |
| mistral_engine.0.0.0.0                                   | 0        |
| mistral_engine_fanout_d7ac68806b5e47b6a992642618e4df6b   | 0        |
| mistral_executor                                         | 0        |
| mistral_executor.0.0.0.0                                 | 0        |
| mistral_executor_fanout_ec9006bc79c04d059bfecfbc7673f46b | 0        |
| st2.actionrunner.canel                                   | 0        |
| st2.actionrunner.req                                     | 0        |
| st2.actionrunner.work                                    | 0        |
| st2.notifiers.work                                       | 0        |
| st2.resultstracker.work                                  | 0        |
| st2.sensor.watch.sensor_container-605d259627             | 0        |
| st2.trigger.watch.St2Timer-544cb11952                    | 0        |
| st2.trigger.watch.TimersController-65bd094078            | 0        |
| st2.trigger.watch.WebhooksController-a80832c156          | 0        |
| st2.trigger_instances_dispatch.rules_engine              | 0        |
+----------------------------------------------------------+----------+
```

**Comment by LindsayHill** [comment]
Looks like the problem is that the `rabbitmqadmin list queues` command here is querying specific parameters from `backing_queue`, and that's deprecated in 3.4 https://groups.google.com/forum/#!topic/rabbitmq-users/ivUAQ1vZsro

I'll make a change here to get this working again. But the actions probably need an overhaul to use a python library rather than CLI commands.
